Repository sprint-FE18-5/Codeit-Sprint-Rolling, pull requests merged in 2025-08, with the labels that each got.

#32 [issue 31] router 구현
  .prettierrc.json
  src/App.jsx
  src/components/Layout/Layout.jsx
  src/main.jsx
Labels: ✨ Feat

#29 [issue 12] 메인, 목록 페이지에서의 헤더 구현 (+ prettier 버그)
  src/assets/icLogo.svg
  src/components/Header/Header.jsx
Labels: ✨ Feat

#35 [issue 18] Card 컴포넌트 구현
  src/App.css
  src/assets/icDelete.svg
  src/components/Card/index.jsx
Labels: ✨ Feat

#34 [issue 30] axios 설정
  src/api/api.md
  src/api/instance.js
  src/components/Layout/Layout.jsx
Labels: ✨ Feat

#46 [issue 45] ToggleButton 컴포넌트 구현
  src/components/Button/ToggleButton.jsx
Labels: ✨ Feat

#60 [issue 25] Dropdown 컴포넌트 리팩토링
  src/assets/icArrowDownDisabled.svg
  src/components/Dropdown/DropdownButton.jsx
  src/components/Dropdown/DropdownContent.jsx
  src/components/Dropdown/DropdownContext.js
  src/components/Dropdown/DropdownItem.jsx
  src/components/Dropdown/DropdownList.jsx
  src/components/Dropdown/DropdownTrigger.jsx
  src/components/Dropdown/Test.jsx
  src/components/Dropdown/index.js
  src/components/Dropdown/index.jsx
  src/components/common/FormMessage.jsx
  src/components/common/index.js
  src/hooks/index.js
  src/hooks/useDropdown.jsx
  src/hooks/useFormValidation.jsx
Labels: ✨ Feat, ♻️ Refactor

#66 [issue 65] Card 컴포넌트 수정
  src/components/Card/index.jsx
Labels: ♻️ Refactor

#86 [issue 77] Input 컴포넌트 스타일 수정
  src/components/Form/Input.jsx
Labels: ♻️ Refactor

#68 [issue 67] CardList 컴포넌트 수정
  src/components/Badge/EmojiBadge/index.jsx
  src/components/CardList/index.jsx
  src/components/ProfileGroup/index.jsx
Labels: ✨ Feat, ♻️ Refactor

#62 [issue 61] Modal 컴포넌트 구현
  src/assets/icProfile.svg
  src/components/Modal/ModalContent/index.jsx
  src/components/Modal/ModalPopup/index.jsx
Labels: ✨ Feat

#74 [issue 72] 버튼 컴포넌트들 수정
  src/components/Button/ArrowButton.jsx
  src/components/Button/ArrowButton/index.jsx
  src/components/Button/CircleButton.jsx
  src/components/Button/CircleButton/index.jsx
  src/components/Button/RegularButton/index.jsx
  src/components/Button/ToggleButton.jsx
  src/components/Button/ToggleButton/index.jsx
  src/components/Button/index.jsx
  src/constants/button/BUTTON_ARROW.js
  src/constants/button/BUTTON_CIRCLE.js
  src/constants/button/BUTTON_COMMON.js
  src/constants/button/BUTTON_REGULAR.js
  src/constants/button/BUTTON_TOGGLE.js
Labels: ♻️ Refactor

#75 [issue 57] Option 컴포넌트 구현
  src/assets/icEnabled.svg
  src/components/Option/ThemeOption.jsx
Labels: ✨ Feat

#84 [issue 76] Dropdown 컴포넌트 스타일 수정
  src/components/Dropdown/DropdownContent.jsx
  src/components/Dropdown/DropdownItem.jsx
  src/components/Dropdown/DropdownTrigger.jsx
  src/components/Dropdown/index.jsx
Labels: ♻️ Refactor

#87 [issue 급해용] Button -> RegularButton 작업
  package-lock.json
  package.json
  src/App.jsx
  src/api/getReactions/index.js
  src/api/postReactions/index.js
  src/assets/icEmoji.svg
  src/components/Header/index.jsx
  src/components/Layout/index.jsx
  src/components/Modal/ModalContent/index.jsx
  src/components/Picker/index.jsx
  src/components/ProfileGroup/index.jsx
  src/components/Share/index.jsx
  src/hooks/useIsMatchURL.js
  src/main.jsx
  src/pages/PostPage.jsx
  src/pages/PostPage/index.jsx
  src/pages/pages.md
  src/utils/utils.md
Labels: 🚚 Rename

#94 [issue 64] 롤링페이퍼에 메시지 보내기 페이지 구현
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Dropdown/DropdownItem.jsx
  src/components/Dropdown/DropdownTrigger.jsx
  src/components/Dropdown/index.jsx
  src/components/Form/Editor/index.jsx
  src/components/Form/FormField/index.jsx
  src/components/Form/FormLayout/index.jsx
  src/components/Option/ProfileOption.jsx
  src/components/Option/ProfileSelector.jsx
  src/pages/PostMessage/index.jsx
  src/utils/Handletter-Regular.woff
  src/utils/NanumMyeongjo-Bold.otf
  src/utils/NanumMyeongjo-Regular.otf
  src/utils/NotoSans-Bold.woff
  src/utils/NotoSans-Regular.woff
Labels: ✨ Feat

#108 [issue 107] 메인페이지 반응형 디자인 적용
  src/pages/MainPage/index.jsx
Labels: 🐛 Fix, ♻️ Refactor

#116 [issue 115] 리스트페이지 스켈레톤 로더 구현
  src/pages/ListPage/index.jsx
Labels: ✨ Feat

#119 [issue 114] tiptap view 에러 방지 로직 추가
  src/components/Form/Editor/index.jsx
Labels: 🐛 Fix
